// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZlYFEESwh5j254uApyJj93-M6v8W41UY',
    appId: '1:1059347487376:web:2a339fb9109275ddcb5615',
    messagingSenderId: '1059347487376',
    projectId: 'ecomart-130d5',
    authDomain: 'ecomart-130d5.firebaseapp.com',
    storageBucket: 'ecomart-130d5.firebasestorage.app',
    measurementId: 'G-RPX6KBSMCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACJCtdoz_WxQUGFYUFMZZta3U3V9CbNK0',
    appId: '1:1059347487376:android:6e3cafdc3d9e86f8cb5615',
    messagingSenderId: '1059347487376',
    projectId: 'ecomart-130d5',
    storageBucket: 'ecomart-130d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHqyrUXluhLokD-ryesh3YI2ICgydiuis',
    appId: '1:1059347487376:ios:fcce099cced8841dcb5615',
    messagingSenderId: '1059347487376',
    projectId: 'ecomart-130d5',
    storageBucket: 'ecomart-130d5.firebasestorage.app',
    iosBundleId: 'com.ecomart.ecomart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHqyrUXluhLokD-ryesh3YI2ICgydiuis',
    appId: '1:1059347487376:ios:fcce099cced8841dcb5615',
    messagingSenderId: '1059347487376',
    projectId: 'ecomart-130d5',
    storageBucket: 'ecomart-130d5.firebasestorage.app',
    iosBundleId: 'com.ecomart.ecomart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZlYFEESwh5j254uApyJj93-M6v8W41UY',
    appId: '1:1059347487376:web:2b76cb2354d3a801cb5615',
    messagingSenderId: '1059347487376',
    projectId: 'ecomart-130d5',
    authDomain: 'ecomart-130d5.firebaseapp.com',
    storageBucket: 'ecomart-130d5.firebasestorage.app',
    measurementId: 'G-Z9ERFG0B4D',
  );
}
